### ISSUE TITLE
Setting the formats

### ISSUE THREAD

**Issue by tristengrant** [tannerdolby/eleventy-plugin-sharp-respimg#4]
Is there a way to set what formats I'd like? Right now it seems to only use webp and jpeg. Some images may be better as a png.

**Comment by tristengrant** [comment]
Can you crop an image? Say, for a thumbnail.

**Comment by tannerdolby** [comment]
👋 thanks for raising an issue! Currently there isn't a way to specify image formats, I originally developed this with webp and jpeg support but never got around to supporting the full spectrum e.g. WebP, JPEG, PNG, AVIF.

I am working on adding this functionality and it should be ready by the end of the week! 

Regarding cropping an image, this plugin doesn't support that but you could open a separate issue and we can discuss it in more detail. I know Sharp has a [tile-based zoom](https://sharp.pixelplumbing.com/api-output#tile) utility which could be used for a thumbnail, but in general thumbnail photos will have a specific dimension regardless of zoom or any tiling effect which should be obtainable from the plugins current functionality.

**Comment by tannerdolby** [comment]
🚨 After giving this some thought, I'm going to advise all users of `eleventy-plugin-sharp-respimg` to migrate to the official responsive image plugin [`eleventy-img`](https://github.com/11ty/eleventy-img) which is created by the Eleventy team. 

This was a tough decision but I think its healthier for the 11ty community to first reach for the official `eleventy-img` before other user contributed options.

I hope this doesn't cause you too much trouble. Happy new year!
